# Name of workflow
name: Test workflow

# Trigger workflow on all pull requests
on:
  pull_request:
    branches:
      - develop

# Jobs to carry out
jobs:
    cypress-run:
        runs-on: ubuntu-24.04
        services:
            mongodb:
              image: mongo:latest
              ports: 
                - 27017:27017
              options: >-
                --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'"
                --health-interval=10s
                --health-timeout=5s
                --health-retries=5
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Install dependencies
            run: npm ci
          # Install npm dependencies, cache them correctly
          # and run all Cypress tests
          - name: Cypress run
            uses: cypress-io/github-action@v6
            with:
              build: npm run build
              start: npm start
              wait-on: 'http://localhost:3001/'
              browser: electron 